<?php require_once('global.php');
if($result = $db->get_results("select * from tb_pending_print_req where isprint = 1")){
	foreach($result as $row) {
			
	}
	$db->query("Insert Into tb_printque (id,city_code, bank_code, branch_code, branch_soleID, micr_account_no, tr_code, cust_name, joint_name1, joint_name2, signatory1, signatory2, signatory3, cust_address1, cust_address2, cust_address3, cust_address4, cust_address5, cust_city, cust_pin, cust_telephone_res, cust_telephone_off, cust_mobile, no_of_books, book_size, bearer_order, atpar, pr_code, chq_no_fronm, chq_no_to, effective_date, issue_date, sr_no_infra, alpha_code, spectial_series, f6, f7, f8, f9, new40, unique_req) select id, city_code, bank_code, branch_code, branch_soleID, micr_account_no, tr_code, cust_name, joint_name1, joint_name2, signatory1, signatory2, signatory3, cust_address1, cust_address2, cust_address3, cust_address4, cust_address5, cust_city, cust_pin, cust_telephone_res, cust_telephone_off, cust_mobile, no_of_books, book_size, bearer_order, atpar, pr_code, chq_no_fronm, chq_no_to, effective_date, issue_date, sr_no_infra, alpha_code, spectial_series, f6, f7, f8, f9, new40, unique_req from tb_pending_print_req where isprint = 1");
	$db->query("Insert Into tb_print_req_collection (id,city_code, bank_code, branch_code, branch_soleID, micr_account_no, tr_code, cust_name, joint_name1, joint_name2, signatory1, signatory2, signatory3, cust_address1, cust_address2, cust_address3, cust_address4, cust_address5, cust_city, cust_pin, cust_telephone_res, cust_telephone_off, cust_mobile, no_of_books, book_size, bearer_order, atpar, pr_code, chq_no_fronm, chq_no_to, effective_date, issue_date, sr_no_infra, alpha_code, spectial_series, f6, f7, f8, f9, new40, unique_req) select id, city_code, bank_code, branch_code, branch_soleID, micr_account_no, tr_code, cust_name, joint_name1, joint_name2, signatory1, signatory2, signatory3, cust_address1, cust_address2, cust_address3, cust_address4, cust_address5, cust_city, cust_pin, cust_telephone_res, cust_telephone_off, cust_mobile, no_of_books, book_size, bearer_order, atpar, pr_code, chq_no_fronm, chq_no_to, effective_date, issue_date, sr_no_infra, alpha_code, spectial_series, f6, f7, f8, f9, new40, unique_req from tb_pending_print_req where isprint = 1");
	$db->query("Delete from tb_pending_print_req where Isprint = 1");
}
?>